package dao;
import java.util.HashSet;
import java.util.Set;
/** * Cliente generated by hbm2java */
public class Cliente  implements java.io.Serializable {
    private int codCliente;
    private String dni;
    private String nombre;
    private String apellido1;
    private String apellido2;
    private String direccion;
    private String municipio;
    private int codProvincia;
    private int codPostal;
    private String telefono;
    private String email;
    private boolean estado;
    
    public Cliente (){}
    public Cliente
        (int codCliente,
         String dni, String nombre, String apellido1, String apellido2, String direccion, String municipio,
         int codProvincia, int codPostal,
         String telefono, String email,
         boolean estado)
    { this.codCliente = codCliente;
      this.dni = dni;
      this.nombre = nombre;
      this.apellido1 = apellido1;
      this.apellido2 = apellido2;
      this.direccion = direccion;
      this.municipio = municipio;
      this.codProvincia = codProvincia;
      this.codPostal = codPostal;
      this.telefono = telefono;
      this.email = email;
      this.estado = estado;}
    
    public int getCodCliente() { return this.codCliente; }
    public void setCodCliente (int codCliente) { this.codCliente = codCliente; }
    public String getDni() { return this.dni; }
    public void setDni(String dni) { this.dni = dni; }
    public String getNombre() { return this.nombre; }
    public void setNombre(String nombre) { this.nombre = nombre; }
    public String getApellido1() { return this.apellido1; }
    public void setApellido1(String apellido1) { this.apellido1 = apellido1; }
    public String getApellido2() { return this.apellido2; }
    public void setApellido2(String apellido2) { this.apellido2 = apellido2; }
    public String getDireccion() { return this.direccion; }
    public void setDireccion (String direccion) { this.direccion = direccion; }
    public String getMunicipio() { return this.municipio; }
    public void setMunicipio (String municipio) { this.municipio = municipio; }
    public int getCodProvincia() { return this.codProvincia; }
    public void setCodProvincia (int codProvincia) { this.codProvincia = codProvincia; }
    public int getCodPostal() { return this.codCliente; }
    public void setCodPostal (int codPostal) { this.codPostal = codPostal; }
    public String getTelefono() { return this.telefono; }
    public void setTelefono(String telefono) { this.telefono = telefono; }
    public String getEmail() { return this.email; }
    public void setEmail(String email) { this.email = email; }
    public boolean getEstado() { return this.estado; }
    public void setEstado(boolean estado) { this.estado = estado; }
}